language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t azhicodan/frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true azhicodan/frontend npm run test